### ISSUE TITLE
Pretrained model weights links broken

### ISSUE THREAD

**Issue by roger-tseng** [awslabs/speech-representations#3]
Hello, just found that the links for both DeCOAR 1.0 and 2.0 are unavailable now.

Would the authors be willing to re-release the model weights to promote better future research?

**Comment by JulianSlzr** [comment]
Hi Roger, apologies for the delay. I've tracked down the artifacts and added them as "releases", and have updated the README.md accordingly. I also suggest you look into the more actively maintained S3PRL toolkit (https://s3prl.github.io/s3prl/), which gives these and other pre-trained representations a standard interface for inference and finetuning.
